language: cpp

git:
  depth: 1000

os:
  - linux
  - osx
sudo: required
dist: trusty
osx_image: xcode8.1

matrix:
  allow_failures:
    - os: osx
  fast_finish: true

install:
  - export PATH=~/.dotnet:$PATH
  - pushd build
  - chmod +x install-powershell.sh
  - ./install-powershell.sh
  - popd

script: 
  - pwsh -File "./build/travis.ps1"









